// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart ' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbRSa-xneE1UuboDGmUoI8uPt90AbwW8I',
    appId: '1:767060789372:web:8d13c7221ffc851b6761f9',
    messagingSenderId: '767060789372',
    projectId: 'phone-auth-yum',
    authDomain: 'phone-auth-yum.firebaseapp.com',
    storageBucket: 'phone-auth-yum.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU-BGJ6u_q1oS-TfRiAwg6oQe-DC2qQrc',
    appId: '1:767060789372:android:9715dc9d5dd707b76761f9',
    messagingSenderId: '767060789372',
    projectId: 'phone-auth-yum',
    storageBucket: 'phone-auth-yum.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbRSa-xneE1UuboDGmUoI8uPt90AbwW8I',
    appId: '1:767060789372:web:1aaaf76710ea63346761f9',
    messagingSenderId: '767060789372',
    projectId: 'phone-auth-yum',
    authDomain: 'phone-auth-yum.firebaseapp.com',
    storageBucket: 'phone-auth-yum.appspot.com',
  );
}
